-- Creating the Superstore Sales database
CREATE DATABASE SUPERSTORE_SALES_DB;

-- Selecting the Superstore Sales database  
USE SUPERSTORE_SALES_DB;

-- Creating a table
CREATE TABLE SALES_DATA (
    ROW_ID INT,
    ORDER_PRIORITY VARCHAR(100),
    DISCOUNT DOUBLE,
    UNIT_PRICE DOUBLE,
    SHIPPING_COST DOUBLE,
    CUSTOMER_ID INT,
    CUSTOMER_NAME VARCHAR(200),
    SHIP_MODE VARCHAR(100),
    CUSTOMER_SEGMENT VARCHAR(100),
    PRODUCT_CATEGORY VARCHAR(255),
    PRODUCT_SUB_CATEGORY VARCHAR(255),
    PRODUCT_CONTAINER VARCHAR(100),
    PRODUCT_NAME VARCHAR(255),
    PRODUCT_BASE_MARGIN DOUBLE NULL,
    REGION VARCHAR(100),
    MANAGER VARCHAR(100),
    STATE_OR_PROVINCE VARCHAR(100),
    CITY VARCHAR(100),
    POSTAL_CODE INT,
    ORDER_DATE VARCHAR(20),
    SHIP_DATE VARCHAR(20),
    PROFIT DOUBLE,
    QUANTITY_ORDERED_NEW INT,
    SALES DOUBLE,
    ORDER_ID INT,
    RETURN_STATUS VARCHAR(20)
);